server:
  port: 8081
  servlet:
    context-path: /AIM
spring:
  banner:
    image:
      location: classpath:MyBanner.png
  main:
    allow-bean-definition-overriding: true #配置允许bean定义覆盖，不然会有两个类创建dataSource数据源，
  application:
    #应用名称
    name: reggie_take_out
  cache:
    redis:
      time-to-live: 1800000
#  shardingsphere:
#    datasource:
#      names:
#        master,slave
#      # 主数据源
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.10.129:3306/reggie?characterEncoding=utf-8
#        username: root
#        password: 142536cyh***CYH/
#      # 从数据源
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.10.130:3306/reggie?characterEncoding=utf-8
#        username: root
#        password: 142536cyh***CYH/
#    masterslave:
#      # 读写分离配置,负载均衡配置
#      load-balance-algorithm-type: round_robin #轮询
#      # 最终的数据源名称
#      name: dataSource
#      # 主库数据源名称
#      master-data-source-name: master
#      # 从库数据源名称列表，多个逗号分隔
#      slave-data-source-names: slave
#    props:
#      sql:
#        show: true #开启SQL显示，默认false
#  redis:
#    host: 192.168.10.129
#    port: 6379
#    database: 0
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/aimsystem?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  #控制上传文件大小的
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID #统一逐渐生成策略，ASSIGN_ID雪花，AUTO自增
#      table-prefix: t_ //表前缀，识别实体类时自动添加前缀



#自定义属性，为转存文件提供位置，方便后期修改
keyh:
  path: H:\ALMIMG\
